---
title: "owner-analysis"
format: html
author: 'Sam Samler'
---
```{r}
## Run this chunk to test exercises ##

library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)

lobster_abundance <- read_csv("../Data/TimeSeries1.csv") %>% 
    mutate(SIZE_MM = na_if(SIZE_MM, -99999))
```
```{r}
ggplot(data = lobster_abundance, 
       aes(x = SIZE_MM)) +
    geom_histogram() +
    facet_wrap(~SITE)
```
```{r}
lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n())
```
```{r}
# line plot
ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_line(aes(color = SITE)) 

# line and point plot
ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_point(aes(color = SITE)) +
  geom_line(aes(color = SITE)) 
```
```{r}
lobster_size_lrg <- lobster_abundance %>%
    filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(SIZE_BIN = if_else(SIZE_MM <= 70, true = "small", false = "large")) %>%
    group_by(SITE, SIZE_BIN) %>%
    summarize(COUNT = n()) %>%
    drop_na()
```
```{r}
# dodged bar plot
ggplot(data = lobster_size_lrg, aes(x = SITE, y = COUNT, fill = SIZE_BIN)) +
       geom_col(position = position_dodge(width = 0.8)) +
    geom_text(aes(label = COUNT),
              position = position_dodge(width = 0.8),
              vjust = -0.3,
              size = 3) +
    scale_fill_viridis_d(option = "D", end = 0.9) +
    theme_minimal(base_size = 12) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(
        title = "Lobster Counts by Site and Size Class",
        x = "Site",
        y = "Count",
        fill = "Size Category"
    )
ggsave("../figs/lobster_abundance_and_size_plot.png", width = 8, height = 5, dpi = 300)
```

